import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import { prisma } from '@/lib/prisma';

// 30 PROFILS DE COURTIERS FICTIFS ULTRA-RÉALISTES
// Avec dates de naissance, tutoiement/vouvoiement, expériences passées
const FICTIONAL_COURTIERS = [
  {
    courtierNumber: 1,
    firstName: "Marc",
    gender: "homme",
    age: 29,
    birthDate: new Date("1995-03-12"),
    city: "Lille",
    joinedAt: new Date("2024-03-15"),
    personality: "compétitif",
    communicationStyle: "direct",
    useTutoiement: true,
    hasTypos: false,
    typoRate: 0.0,
    isMorningPerson: true,
    emojiUsage: "low",
    affinities: [5, 12, 23],
    background: "Ancien commercial en assurance",
    previousCompanies: "AXA, Generali",
    monthlyEarnings: 8500,
    travelPlans: "Week-end à Amsterdam en mars",
    lifeContext: "Économise pour acheter un appart"
  },
  {
    courtierNumber: 2,
    firstName: "Sophie",
    gender: "femme",
    age: 25,
    birthDate: new Date("1999-07-22"),
    city: "Paris",
    joinedAt: new Date("2024-06-10"),
    personality: "joviale",
    communicationStyle: "émojis",
    useTutoiement: true,
    hasTypos: true,
    typoRate: 0.08,
    isMorningPerson: false,
    emojiUsage: "high",
    affinities: [7, 15, 28],
    background: "Première expérience en télévente",
    previousCompanies: "Aucune (première expérience)",
    monthlyEarnings: 4200,
    travelPlans: null,
    lifeContext: "Galère un peu en fin de mois"
  },
  {
    courtierNumber: 3,
    firstName: "Ahmed",
    gender: "homme",
    age: 34,
    birthDate: new Date("1990-11-05"),
    city: "Marseille",
    joinedAt: new Date("2024-01-20"),
    personality: "sérieux",
    communicationStyle: "formel",
    useTutoiement: false, // Vouvoie
    hasTypos: false,
    typoRate: 0.0,
    isMorningPerson: true,
    emojiUsage: "none",
    affinities: [9, 17],
    background: "Reconversion depuis la vente automobile",
    previousCompanies: "Renault, Peugeot",
    monthlyEarnings: 9800,
    travelPlans: null,
    lifeContext: "Père de 2 enfants, stable"
  },
  {
    courtierNumber: 4,
    firstName: "Lucie",
    gender: "femme",
    age: 27,
    birthDate: new Date("1997-05-18"),
    city: "Lyon",
    joinedAt: new Date("2024-09-05"),
    personality: "motivée",
    communicationStyle: "enthousiaste",
    useTutoiement: true,
    hasTypos: false,
    typoRate: 0.02,
    isMorningPerson: true,
    emojiUsage: "moderate",
    affinities: [2, 11, 19],
    background: "Ancienne téléconseillère Orange",
    previousCompanies: "Orange",
    monthlyEarnings: 5600,
    travelPlans: "Ski en février",
    lifeContext: "Monte en puissance, ambitieuse"
  },
  {
    courtierNumber: 5,
    firstName: "Thomas",
    gender: "homme",
    age: 31,
    birthDate: new Date("1993-09-30"),
    city: "Toulouse",
    joinedAt: new Date("2024-02-28"),
    personality: "blagueur",
    communicationStyle: "décontracté",
    useTutoiement: true,
    hasTypos: true,
    typoRate: 0.10,
    isMorningPerson: false,
    emojiUsage: "moderate",
    affinities: [1, 8, 14],
    background: "Ex-serveur reconverti",
    previousCompanies: "Restauration (Buffalo Grill)",
    monthlyEarnings: 6100,
    travelPlans: null,
    lifeContext: "Content d'avoir changé de secteur"
  },
  {
    courtierNumber: 6,
    firstName: "Nadia",
    gender: "femme",
    age: 28,
    birthDate: new Date("1996-01-14"),
    city: "Bordeaux",
    joinedAt: new Date("2025-10-12"),
    personality: "discrète",
    communicationStyle: "abrégé",
    useTutoiement: true,
    hasTypos: false,
    typoRate: 0.03,
    isMorningPerson: true,
    emojiUsage: "low",
    affinities: [3, 20],
    background: "Ex-assistante administrative",
    previousCompanies: "Cabinet comptable",
    monthlyEarnings: 5100,
    travelPlans: null,
    lifeContext: "Besoin de changement, veut gagner plus"
  },
  {
    courtierNumber: 7,
    firstName: "Julien",
    gender: "homme",
    age: 26,
    birthDate: new Date("1998-08-03"),
    city: "Nantes",
    joinedAt: new Date("2025-07-22"),
    personality: "râleur",
    communicationStyle: "direct",
    useTutoiement: true,
    hasTypos: true,
    typoRate: 0.12,
    isMorningPerson: false,
    emojiUsage: "low",
    affinities: [2, 5],
    background: "Ex-vendeur Fnac",
    previousCompanies: "Fnac, Boulanger",
    monthlyEarnings: 4800,
    travelPlans: null,
    lifeContext: "Se plaint souvent mais efficace"
  },
  {
    courtierNumber: 8,
    firstName: "Émilie",
    gender: "femme",
    age: 30,
    birthDate: new Date("1994-12-25"),
    city: "Strasbourg",
    joinedAt: new Date("2024-04-16"),
    personality: "bienveillante",
    communicationStyle: "émojis",
    useTutoiement: true,
    hasTypos: false,
    typoRate: 0.04,
    isMorningPerson: true,
    emojiUsage: "high",
    affinities: [4, 5, 12],
    background: "Reconversion après congé parental",
    previousCompanies: "SFR",
    monthlyEarnings: 7200,
    travelPlans: null,
    lifeContext: "Mère de famille, motivée"
  },
  {
    courtierNumber: 9,
    firstName: "Karim",
    gender: "homme",
    age: 33,
    birthDate: new Date("1991-06-08"),
    city: "Nice",
    joinedAt: new Date("2024-05-20"),
    personality: "leader",
    communicationStyle: "direct",
    useTutoiement: false, // Vouvoie
    hasTypos: false,
    typoRate: 0.0,
    isMorningPerson: true,
    emojiUsage: "none",
    affinities: [3, 16, 24],
    background: "Ex-responsable d'équipe télémarketing",
    previousCompanies: "Teleperformance",
    monthlyEarnings: 10500,
    travelPlans: null,
    lifeContext: "Ambitieux, vise le top"
  },
  {
    courtierNumber: 10,
    firstName: "Anaïs",
    gender: "femme",
    age: 24,
    birthDate: new Date("2000-02-14"),
    city: "Rennes",
    joinedAt: new Date("2025-11-03"),
    personality: "timide",
    communicationStyle: "abrégé",
    useTutoiement: false, // Vouvoie
    hasTypos: true,
    typoRate: 0.06,
    isMorningPerson: false,
    emojiUsage: "low",
    affinities: [6, 15],
    background: "Sortie d'école de commerce",
    previousCompanies: "Stage chez Bouygues Telecom",
    monthlyEarnings: 3800,
    travelPlans: null,
    lifeContext: "Débute, un peu stressée"
  },
  {
    courtierNumber: 11,
    firstName: "Maxime",
    gender: "homme",
    age: 28,
    birthDate: new Date("1996-10-19"),
    city: "Montpellier",
    joinedAt: new Date("2024-08-14"),
    personality: "décontracté",
    communicationStyle: "décontracté",
    useTutoiement: true,
    hasTypos: true,
    typoRate: 0.09,
    isMorningPerson: false,
    emojiUsage: "moderate",
    affinities: [4, 18, 22],
    background: "Ex-coach sportif reconverti",
    previousCompanies: "Basic-Fit",
    monthlyEarnings: 6400,
    travelPlans: "Surf au Portugal cet été",
    lifeContext: "Décontracté, aime le lifestyle"
  },
  {
    courtierNumber: 12,
    firstName: "Camille",
    gender: "femme",
    age: 32,
    birthDate: new Date("1992-04-27"),
    city: "Toulon",
    joinedAt: new Date("2024-03-08"),
    personality: "ambitieuse",
    communicationStyle: "enthousiaste",
    useTutoiement: true,
    hasTypos: false,
    typoRate: 0.02,
    isMorningPerson: true,
    emojiUsage: "moderate",
    affinities: [1, 8, 21],
    background: "Ex-commerciale en immobilier",
    previousCompanies: "Century 21, Orpi",
    monthlyEarnings: 9200,
    travelPlans: "New York en avril",
    lifeContext: "Performante, vise les records"
  },
  {
    courtierNumber: 13,
    firstName: "Dylan",
    gender: "homme",
    age: 23,
    birthDate: new Date("2001-11-11"),
    city: "Grenoble",
    joinedAt: new Date("2025-12-01"),
    personality: "impulsif",
    communicationStyle: "abrégé",
    useTutoiement: true,
    hasTypos: true,
    typoRate: 0.11,
    isMorningPerson: false,
    emojiUsage: "moderate",
    affinities: [7, 11],
    background: "Premier vrai job",
    previousCompanies: "Jobs d'été (McDo, Decathlon)",
    monthlyEarnings: 3200,
    travelPlans: null,
    lifeContext: "Jeune, apprend sur le tas"
  },
  {
    courtierNumber: 14,
    firstName: "Inès",
    gender: "femme",
    age: 29,
    birthDate: new Date("1995-07-09"),
    city: "Angers",
    joinedAt: new Date("2024-02-15"),
    personality: "méthodique",
    communicationStyle: "formel",
    useTutoiement: false, // Vouvoie
    hasTypos: false,
    typoRate: 0.0,
    isMorningPerson: true,
    emojiUsage: "none",
    affinities: [5, 19],
    background: "Ex-assistante commerciale",
    previousCompanies: "Veolia",
    monthlyEarnings: 7800,
    travelPlans: null,
    lifeContext: "Organisée, précise"
  },
  {
    courtierNumber: 15,
    firstName: "Romain",
    gender: "homme",
    age: 30,
    birthDate: new Date("1994-03-16"),
    city: "Dijon",
    joinedAt: new Date("2024-07-19"),
    personality: "stressé",
    communicationStyle: "émojis",
    useTutoiement: true,
    hasTypos: true,
    typoRate: 0.07,
    isMorningPerson: false,
    emojiUsage: "high",
    affinities: [2, 10, 17],
    background: "Reconversion depuis la restauration",
    previousCompanies: "Quick, KFC",
    monthlyEarnings: 5300,
    travelPlans: null,
    lifeContext: "Stressé par les performances"
  },
  {
    courtierNumber: 16,
    firstName: "Clara",
    gender: "femme",
    age: 26,
    birthDate: new Date("1998-09-21"),
    city: "Reims",
    joinedAt: new Date("2025-08-30"),
    personality: "positive",
    communicationStyle: "enthousiaste",
    useTutoiement: true,
    hasTypos: false,
    typoRate: 0.03,
    isMorningPerson: true,
    emojiUsage: "high",
    affinities: [4, 9, 23],
    background: "Ex-hôtesse d'accueil",
    previousCompanies: "Aéroport Charles de Gaulle",
    monthlyEarnings: 6700,
    travelPlans: null,
    lifeContext: "Toujours souriante et motivée"
  },
  {
    courtierNumber: 17,
    firstName: "Lucas",
    gender: "homme",
    age: 27,
    birthDate: new Date("1997-01-30"),
    city: "Le Havre",
    joinedAt: new Date("2024-06-25"),
    personality: "analytique",
    communicationStyle: "formel",
    useTutoiement: false, // Vouvoie
    hasTypos: false,
    typoRate: 0.0,
    isMorningPerson: true,
    emojiUsage: "none",
    affinities: [3, 9, 15],
    background: "Ex-analyste financier reconverti",
    previousCompanies: "BNP Paribas",
    monthlyEarnings: 8900,
    travelPlans: null,
    lifeContext: "Méthodique, analyse tout"
  },
  {
    courtierNumber: 18,
    firstName: "Léa",
    gender: "femme",
    age: 25,
    birthDate: new Date("1999-05-05"),
    city: "Clermont-Ferrand",
    joinedAt: new Date("2025-09-17"),
    personality: "hésitante",
    communicationStyle: "abrégé",
    useTutoiement: true,
    hasTypos: true,
    typoRate: 0.08,
    isMorningPerson: false,
    emojiUsage: "low",
    affinities: [11, 20],
    background: "Ex-vendeuse en boutique",
    previousCompanies: "Zara, H&M",
    monthlyEarnings: 4500,
    travelPlans: null,
    lifeContext: "Manque de confiance mais progresse"
  },
  {
    courtierNumber: 19,
    firstName: "Antoine",
    gender: "homme",
    age: 35,
    birthDate: new Date("1989-12-12"),
    city: "Tours",
    joinedAt: new Date("2024-01-10"),
    personality: "enthousiaste",
    communicationStyle: "direct",
    useTutoiement: true,
    hasTypos: false,
    typoRate: 0.02,
    isMorningPerson: true,
    emojiUsage: "moderate",
    affinities: [4, 14, 26],
    background: "Ex-commercial terrain",
    previousCompanies: "Engie, Total",
    monthlyEarnings: 11200,
    travelPlans: "Voyage Thaïlande en mars",
    lifeContext: "Top performer, très motivé"
  },
  {
    courtierNumber: 20,
    firstName: "Sarah",
    gender: "femme",
    age: 31,
    birthDate: new Date("1993-08-24"),
    city: "Limoges",
    joinedAt: new Date("2024-11-03"),
    personality: "empathique",
    communicationStyle: "émojis",
    useTutoiement: true,
    hasTypos: true,
    typoRate: 0.06,
    isMorningPerson: true,
    emojiUsage: "high",
    affinities: [6, 8, 18],
    background: "Ex-infirmière reconvertie",
    previousCompanies: "CHU Limoges",
    monthlyEarnings: 6900,
    travelPlans: null,
    lifeContext: "Empathique, écoute bien"
  },
  {
    courtierNumber: 21,
    firstName: "Kevin",
    gender: "homme",
    age: 29,
    birthDate: new Date("1995-04-17"),
    city: "Brest",
    joinedAt: new Date("2024-03-22"),
    personality: "pragmatique",
    communicationStyle: "direct",
    useTutoiement: true,
    hasTypos: false,
    typoRate: 0.04,
    isMorningPerson: false,
    emojiUsage: "low",
    affinities: [12, 19, 27],
    background: "Ex-technicien reconverti",
    previousCompanies: "Orange (technicien fibre)",
    monthlyEarnings: 7600,
    travelPlans: null,
    lifeContext: "Pragmatique, va droit au but"
  },
  {
    courtierNumber: 22,
    firstName: "Manon",
    gender: "femme",
    age: 24,
    birthDate: new Date("2000-06-06"),
    city: "Amiens",
    joinedAt: new Date("2025-10-25"),
    personality: "spontanée",
    communicationStyle: "décontracté",
    useTutoiement: true,
    hasTypos: true,
    typoRate: 0.10,
    isMorningPerson: false,
    emojiUsage: "high",
    affinities: [11, 13, 25],
    background: "Première expérience professionnelle",
    previousCompanies: "Aucune",
    monthlyEarnings: 4100,
    travelPlans: null,
    lifeContext: "Spontanée, naturelle"
  },
  {
    courtierNumber: 23,
    firstName: "Benjamin",
    gender: "homme",
    age: 32,
    birthDate: new Date("1992-10-02"),
    city: "Perpignan",
    joinedAt: new Date("2024-02-20"),
    personality: "calme",
    communicationStyle: "abrégé",
    useTutoiement: true,
    hasTypos: false,
    typoRate: 0.02,
    isMorningPerson: true,
    emojiUsage: "low",
    affinities: [1, 16, 28],
    background: "Ex-vendeur en concession auto",
    previousCompanies: "Mercedes, BMW",
    monthlyEarnings: 8300,
    travelPlans: null,
    lifeContext: "Calme, posé, efficace"
  },
  {
    courtierNumber: 24,
    firstName: "Chloé",
    gender: "femme",
    age: 28,
    birthDate: new Date("1996-11-28"),
    city: "Besançon",
    joinedAt: new Date("2024-05-15"),
    personality: "battante",
    communicationStyle: "enthousiaste",
    useTutoiement: true,
    hasTypos: false,
    typoRate: 0.01,
    isMorningPerson: true,
    emojiUsage: "moderate",
    affinities: [9, 12, 19],
    background: "Ex-commerciale SFR",
    previousCompanies: "SFR",
    monthlyEarnings: 9600,
    travelPlans: "Week-end Barcelone",
    lifeContext: "Battante, ne lâche rien"
  },
  {
    courtierNumber: 25,
    firstName: "Alexandre",
    gender: "homme",
    age: 26,
    birthDate: new Date("1998-02-28"),
    city: "Orléans",
    joinedAt: new Date("2025-11-20"),
    personality: "joueur",
    communicationStyle: "décontracté",
    useTutoiement: true,
    hasTypos: true,
    typoRate: 0.09,
    isMorningPerson: false,
    emojiUsage: "moderate",
    affinities: [5, 11, 22],
    background: "Ex-gamer devenu télévendeur",
    previousCompanies: "Streaming Twitch (pas sérieux)",
    monthlyEarnings: 5800,
    travelPlans: null,
    lifeContext: "Aime les challenges, esprit gamer"
  },
  {
    courtierNumber: 26,
    firstName: "Morgane",
    gender: "femme",
    age: 33,
    birthDate: new Date("1991-09-15"),
    city: "Mulhouse",
    joinedAt: new Date("2024-04-30"),
    personality: "perfectionniste",
    communicationStyle: "formel",
    useTutoiement: false, // Vouvoie
    hasTypos: false,
    typoRate: 0.0,
    isMorningPerson: true,
    emojiUsage: "none",
    affinities: [14, 17, 19],
    background: "Ex-gestionnaire de patrimoine",
    previousCompanies: "Crédit Agricole",
    monthlyEarnings: 10800,
    travelPlans: null,
    lifeContext: "Perfectionniste, exigeante"
  },
  {
    courtierNumber: 27,
    firstName: "Mathieu",
    gender: "homme",
    age: 30,
    birthDate: new Date("1994-07-07"),
    city: "Caen",
    joinedAt: new Date("2024-08-08"),
    personality: "opportuniste",
    communicationStyle: "direct",
    useTutoiement: true,
    hasTypos: false,
    typoRate: 0.03,
    isMorningPerson: false,
    emojiUsage: "low",
    affinities: [21, 23, 29],
    background: "Ex-commercial B2B",
    previousCompanies: "Manpower",
    monthlyEarnings: 8700,
    travelPlans: null,
    lifeContext: "Opportuniste, saisit les occasions"
  },
  {
    courtierNumber: 28,
    firstName: "Jade",
    gender: "femme",
    age: 27,
    birthDate: new Date("1997-12-03"),
    city: "Nancy",
    joinedAt: new Date("2024-09-12"),
    personality: "rêveuse",
    communicationStyle: "émojis",
    useTutoiement: true,
    hasTypos: true,
    typoRate: 0.07,
    isMorningPerson: false,
    emojiUsage: "high",
    affinities: [2, 20, 23],
    background: "Ex-artiste peintre reconvertie",
    previousCompanies: "Indépendante (art)",
    monthlyEarnings: 5500,
    travelPlans: "Voyage artistique en Italie",
    lifeContext: "Rêveuse mais motivée par l'argent"
  },
  {
    courtierNumber: 29,
    firstName: "Nicolas",
    gender: "homme",
    age: 36,
    birthDate: new Date("1988-05-20"),
    city: "Metz",
    joinedAt: new Date("2024-01-15"),
    personality: "sarcastique",
    communicationStyle: "direct",
    useTutoiement: true,
    hasTypos: false,
    typoRate: 0.04,
    isMorningPerson: true,
    emojiUsage: "low",
    affinities: [7, 21, 27],
    background: "Ex-prof reconverti (burnout)",
    previousCompanies: "Éducation Nationale",
    monthlyEarnings: 9100,
    travelPlans: null,
    lifeContext: "Sarcastique mais performant"
  },
  {
    courtierNumber: 30,
    firstName: "Emma",
    gender: "femme",
    age: 25,
    birthDate: new Date("1999-10-10"),
    city: "Boulogne-Billancourt",
    joinedAt: new Date("2025-12-05"),
    personality: "optimiste",
    communicationStyle: "enthousiaste",
    useTutoiement: true,
    hasTypos: false,
    typoRate: 0.05,
    isMorningPerson: true,
    emojiUsage: "high",
    affinities: [4, 16, 24],
    background: "Ex-chargée de clientèle banque",
    previousCompanies: "BNP Paribas",
    monthlyEarnings: 6200,
    travelPlans: null,
    lifeContext: "Optimiste, voit toujours le positif"
  },
];

// Génère l'historique des gains mensuels depuis la date d'arrivée
function generateEarningsHistory(joinedAt: Date, monthlyAverage: number): string {
  const history: Record<string, number> = {};
  const start = new Date(joinedAt);
  const now = new Date();

  let current = new Date(start);
  while (current <= now) {
    const key = `${current.getFullYear()}-${String(current.getMonth() + 1).padStart(2, '0')}`;
    // Variation de ±20% autour de la moyenne
    const variation = (Math.random() - 0.5) * 0.4;
    history[key] = Math.round(monthlyAverage * (1 + variation));
    current.setMonth(current.getMonth() + 1);
  }

  return JSON.stringify(history);
}

export async function POST(request: NextRequest) {
  const session = await getServerSession(authOptions);

  if (!session || session.user.role !== 'ADMIN') {
    return NextResponse.json({ error: 'Non autorisé - Admin uniquement' }, { status: 403 });
  }

  try {
    // Supprimer tous les courtiers fictifs existants
    await prisma.fictionalCourtier.deleteMany({});

    // Créer les 30 courtiers
    const createdCourtiers = [];
    for (const courtier of FICTIONAL_COURTIERS) {
      const created = await prisma.fictionalCourtier.create({
        data: {
          courtierNumber: courtier.courtierNumber,
          firstName: courtier.firstName,
          gender: courtier.gender,
          age: courtier.age,
          birthDate: courtier.birthDate,
          city: courtier.city,
          joinedAt: courtier.joinedAt,
          personality: courtier.personality,
          communicationStyle: courtier.communicationStyle,
          useTutoiement: courtier.useTutoiement,
          hasTypos: courtier.hasTypos,
          typoRate: courtier.typoRate,
          isMorningPerson: courtier.isMorningPerson,
          emojiUsage: courtier.emojiUsage,
          affinitiesJson: JSON.stringify(courtier.affinities),
          background: courtier.background,
          previousCompanies: courtier.previousCompanies,
          monthlyEarnings: courtier.monthlyEarnings,
          earningsHistory: generateEarningsHistory(courtier.joinedAt, courtier.monthlyEarnings),
          travelPlans: courtier.travelPlans,
          lifeContext: courtier.lifeContext,
        },
      });
      createdCourtiers.push(created);
    }

    return NextResponse.json({
      success: true,
      message: `${createdCourtiers.length} courtiers fictifs initialisés avec succès`,
      courtiers: createdCourtiers.map(c => ({
        number: c.courtierNumber,
        firstName: c.firstName,
        birthDate: c.birthDate,
        useTutoiement: c.useTutoiement,
      })),
    });
  } catch (error) {
    console.error('Erreur lors de l\'initialisation des courtiers:', error);
    return NextResponse.json({ error: 'Erreur serveur' }, { status: 500 });
  }
}
